name: "📂 Upload Materiale"
description: "Trimite materiale pentru a ajuta urmatoarele generații"
title: "[Material] - "
labels: ["materiale"]
body:
  - type: input
    id: nume
    attributes:
      label: "Numele materialului"
      description: "Cum vrei să apară materialul?"
      placeholder: "Ex: Seminar Algoritmi_Grafuri"
    validations:
      required: true
      
  - type: input
    id: grupa
    attributes:
      label: "Grupa/Seria pentru care este destinat materialul"
      description: "Ex: seria/grupa unde se aplică materialul"
      placeholder: "Ex: Seriile 13 & 15"
    validations:
      required: true

  - type: input
    id: materie
    attributes:
      label: "Materia"
      description: "Cărei materii îi corespunde acest material"
      placeholder: "Ex: POO"
    validations:
      required: true

  - type: input
    id: prof
    attributes:
      label: "Profesorul titular"
      description: "Numele profesorului de la curs"
      placeholder: "Ex: Ionescu"
    validations:
      required: true
      
  - type: textarea
    id: descriere
    attributes:
      label: "Descriere"
      description: "Descrie pe scurt materialul."
      placeholder: "Ex: Note de curs, capitolul 3"
    validations:
      required: false

  - type: markdown
    attributes:
      value: "👉 **Atașează fișierul la issue (drag & drop sau upload)**"
